/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PhotosRouteImport } from './routes/photos'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as EstimatesRouteImport } from './routes/estimates'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as BrigadesRouteImport } from './routes/brigades'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsIndexRouteImport } from './routes/tools.index'
import { Route as TasksIndexRouteImport } from './routes/tasks.index'
import { Route as ObjectsIndexRouteImport } from './routes/objects.index'
import { Route as ToolsArchiveRouteImport } from './routes/tools.archive'
import { Route as ToolsToolIdRouteImport } from './routes/tools.$toolId'
import { Route as TasksTaskIdRouteImport } from './routes/tasks.$taskId'
import { Route as PhotosPhotoIdRouteImport } from './routes/photos_.$photoId'
import { Route as ObjectsObjectIdIndexRouteImport } from './routes/objects.$objectId.index'
import { Route as ObjectsObjectIdStagesStageIdRouteImport } from './routes/objects.$objectId.stages.$stageId'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotosRoute = PhotosRouteImport.update({
  id: '/photos',
  path: '/photos',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const EstimatesRoute = EstimatesRouteImport.update({
  id: '/estimates',
  path: '/estimates',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BrigadesRoute = BrigadesRouteImport.update({
  id: '/brigades',
  path: '/brigades',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjectsIndexRoute = ObjectsIndexRouteImport.update({
  id: '/objects/',
  path: '/objects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsArchiveRoute = ToolsArchiveRouteImport.update({
  id: '/tools/archive',
  path: '/tools/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsToolIdRoute = ToolsToolIdRouteImport.update({
  id: '/tools/$toolId',
  path: '/tools/$toolId',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksTaskIdRoute = TasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotosPhotoIdRoute = PhotosPhotoIdRouteImport.update({
  id: '/photos_/$photoId',
  path: '/photos/$photoId',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjectsObjectIdIndexRoute = ObjectsObjectIdIndexRouteImport.update({
  id: '/objects/$objectId/',
  path: '/objects/$objectId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjectsObjectIdStagesStageIdRoute =
  ObjectsObjectIdStagesStageIdRouteImport.update({
    id: '/objects/$objectId/stages/$stageId',
    path: '/objects/$objectId/stages/$stageId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/brigades': typeof BrigadesRoute
  '/chat': typeof ChatRoute
  '/customers': typeof CustomersRoute
  '/documents': typeof DocumentsRoute
  '/estimates': typeof EstimatesRoute
  '/expenses': typeof ExpensesRoute
  '/photos': typeof PhotosRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/photos/$photoId': typeof PhotosPhotoIdRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/tools/$toolId': typeof ToolsToolIdRoute
  '/tools/archive': typeof ToolsArchiveRoute
  '/objects/': typeof ObjectsIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/objects/$objectId/': typeof ObjectsObjectIdIndexRoute
  '/objects/$objectId/stages/$stageId': typeof ObjectsObjectIdStagesStageIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/brigades': typeof BrigadesRoute
  '/chat': typeof ChatRoute
  '/customers': typeof CustomersRoute
  '/documents': typeof DocumentsRoute
  '/estimates': typeof EstimatesRoute
  '/expenses': typeof ExpensesRoute
  '/photos': typeof PhotosRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/photos/$photoId': typeof PhotosPhotoIdRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/tools/$toolId': typeof ToolsToolIdRoute
  '/tools/archive': typeof ToolsArchiveRoute
  '/objects': typeof ObjectsIndexRoute
  '/tasks': typeof TasksIndexRoute
  '/tools': typeof ToolsIndexRoute
  '/objects/$objectId': typeof ObjectsObjectIdIndexRoute
  '/objects/$objectId/stages/$stageId': typeof ObjectsObjectIdStagesStageIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/brigades': typeof BrigadesRoute
  '/chat': typeof ChatRoute
  '/customers': typeof CustomersRoute
  '/documents': typeof DocumentsRoute
  '/estimates': typeof EstimatesRoute
  '/expenses': typeof ExpensesRoute
  '/photos': typeof PhotosRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/photos_/$photoId': typeof PhotosPhotoIdRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/tools/$toolId': typeof ToolsToolIdRoute
  '/tools/archive': typeof ToolsArchiveRoute
  '/objects/': typeof ObjectsIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/objects/$objectId/': typeof ObjectsObjectIdIndexRoute
  '/objects/$objectId/stages/$stageId': typeof ObjectsObjectIdStagesStageIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/brigades'
    | '/chat'
    | '/customers'
    | '/documents'
    | '/estimates'
    | '/expenses'
    | '/photos'
    | '/settings'
    | '/users'
    | '/photos/$photoId'
    | '/tasks/$taskId'
    | '/tools/$toolId'
    | '/tools/archive'
    | '/objects/'
    | '/tasks/'
    | '/tools/'
    | '/objects/$objectId/'
    | '/objects/$objectId/stages/$stageId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/brigades'
    | '/chat'
    | '/customers'
    | '/documents'
    | '/estimates'
    | '/expenses'
    | '/photos'
    | '/settings'
    | '/users'
    | '/photos/$photoId'
    | '/tasks/$taskId'
    | '/tools/$toolId'
    | '/tools/archive'
    | '/objects'
    | '/tasks'
    | '/tools'
    | '/objects/$objectId'
    | '/objects/$objectId/stages/$stageId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/brigades'
    | '/chat'
    | '/customers'
    | '/documents'
    | '/estimates'
    | '/expenses'
    | '/photos'
    | '/settings'
    | '/users'
    | '/photos_/$photoId'
    | '/tasks/$taskId'
    | '/tools/$toolId'
    | '/tools/archive'
    | '/objects/'
    | '/tasks/'
    | '/tools/'
    | '/objects/$objectId/'
    | '/objects/$objectId/stages/$stageId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BrigadesRoute: typeof BrigadesRoute
  ChatRoute: typeof ChatRoute
  CustomersRoute: typeof CustomersRoute
  DocumentsRoute: typeof DocumentsRoute
  EstimatesRoute: typeof EstimatesRoute
  ExpensesRoute: typeof ExpensesRoute
  PhotosRoute: typeof PhotosRoute
  SettingsRoute: typeof SettingsRoute
  UsersRoute: typeof UsersRoute
  PhotosPhotoIdRoute: typeof PhotosPhotoIdRoute
  TasksTaskIdRoute: typeof TasksTaskIdRoute
  ToolsToolIdRoute: typeof ToolsToolIdRoute
  ToolsArchiveRoute: typeof ToolsArchiveRoute
  ObjectsIndexRoute: typeof ObjectsIndexRoute
  TasksIndexRoute: typeof TasksIndexRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
  ObjectsObjectIdIndexRoute: typeof ObjectsObjectIdIndexRoute
  ObjectsObjectIdStagesStageIdRoute: typeof ObjectsObjectIdStagesStageIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photos': {
      id: '/photos'
      path: '/photos'
      fullPath: '/photos'
      preLoaderRoute: typeof PhotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estimates': {
      id: '/estimates'
      path: '/estimates'
      fullPath: '/estimates'
      preLoaderRoute: typeof EstimatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brigades': {
      id: '/brigades'
      path: '/brigades'
      fullPath: '/brigades'
      preLoaderRoute: typeof BrigadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objects/': {
      id: '/objects/'
      path: '/objects'
      fullPath: '/objects/'
      preLoaderRoute: typeof ObjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/archive': {
      id: '/tools/archive'
      path: '/tools/archive'
      fullPath: '/tools/archive'
      preLoaderRoute: typeof ToolsArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/$toolId': {
      id: '/tools/$toolId'
      path: '/tools/$toolId'
      fullPath: '/tools/$toolId'
      preLoaderRoute: typeof ToolsToolIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$taskId': {
      id: '/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof TasksTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photos_/$photoId': {
      id: '/photos_/$photoId'
      path: '/photos/$photoId'
      fullPath: '/photos/$photoId'
      preLoaderRoute: typeof PhotosPhotoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objects/$objectId/': {
      id: '/objects/$objectId/'
      path: '/objects/$objectId'
      fullPath: '/objects/$objectId/'
      preLoaderRoute: typeof ObjectsObjectIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objects/$objectId/stages/$stageId': {
      id: '/objects/$objectId/stages/$stageId'
      path: '/objects/$objectId/stages/$stageId'
      fullPath: '/objects/$objectId/stages/$stageId'
      preLoaderRoute: typeof ObjectsObjectIdStagesStageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BrigadesRoute: BrigadesRoute,
  ChatRoute: ChatRoute,
  CustomersRoute: CustomersRoute,
  DocumentsRoute: DocumentsRoute,
  EstimatesRoute: EstimatesRoute,
  ExpensesRoute: ExpensesRoute,
  PhotosRoute: PhotosRoute,
  SettingsRoute: SettingsRoute,
  UsersRoute: UsersRoute,
  PhotosPhotoIdRoute: PhotosPhotoIdRoute,
  TasksTaskIdRoute: TasksTaskIdRoute,
  ToolsToolIdRoute: ToolsToolIdRoute,
  ToolsArchiveRoute: ToolsArchiveRoute,
  ObjectsIndexRoute: ObjectsIndexRoute,
  TasksIndexRoute: TasksIndexRoute,
  ToolsIndexRoute: ToolsIndexRoute,
  ObjectsObjectIdIndexRoute: ObjectsObjectIdIndexRoute,
  ObjectsObjectIdStagesStageIdRoute: ObjectsObjectIdStagesStageIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
